import Link from "next/link";
import { MobileNavigation } from "./mobile-navigation";

export function Brand() {
  return <Link href="/" className="brand" aria-label="Luminary Educational Services home"><span className="brand-logo-full"><img src="/luminary-logo-source.webp" alt="" width={261} height={400} decoding="async" /></span><span className="brand-copy"><strong>LUMINARY</strong><small>Educational Services</small></span></Link>;
}

export function Header() {
  return <header className="site-header"><div className="shell header-inner"><Brand /><nav className="desktop-nav" aria-label="Primary navigation"><Link href="/">Home</Link><Link href="/#about">About</Link><Link href="/courses/">Courses</Link><Link href="/#wes-evaluation">WES Evaluation</Link><Link href="/#enquiry">Contact</Link></nav><a className="header-cta" href="/#enquiry">Book consultation <span>↗</span></a><MobileNavigation /></div></header>;
}

export function LeadForm() {
  return <section className="section contact-section" id="enquiry"><div className="shell contact-grid"><div className="contact-copy"><p className="eyebrow light">Speak with a counsellor</p><h2>Find the right pathway in Punjab.</h2><p>Tell us your current education, district and goal. Counselling is available in Punjabi and English, so your family can discuss every option comfortably.</p><div className="language-pills"><span>ਪੰਜਾਬੀ</span><span>English</span></div><div className="contact-list"><a href="tel:+917053732000"><span>Call</span><strong>+91 70537 32000</strong></a><a href="tel:+919914099906"><span>Call</span><strong>+91 99140 99906</strong></a><a href="mailto:luminaryedu@zohomail.com"><span>Email</span><strong>luminaryedu@zohomail.com</strong></a></div></div><form className="lead-form" action="https://wa.me/917053732000" method="get" target="_blank"><div className="form-row"><label>Full name<input type="text" name="name" placeholder="Your name" required /></label><label>Phone number<input type="tel" name="phone" placeholder="+91 00000 00000" required /></label></div><div className="form-row"><label>Punjab district<input type="text" name="district" placeholder="e.g. Moga, Ludhiana" /></label><label>Current qualification<input type="text" name="qualification" placeholder="e.g. 12th, graduation" /></label></div><div className="form-row"><label>I am interested in<select name="interest" defaultValue=""><option value="" disabled>Select a pathway</option><option>Degree Admission</option><option>Nursing / Skill Course</option><option>ITI Skill Course</option><option>WES Evaluation Assistance</option></select></label><label>Preferred language<select name="language" defaultValue=""><option value="" disabled>Select language</option><option>Punjabi</option><option>English</option></select></label></div><label>Your question <textarea name="text" placeholder="Tell us a little about your education and goal" rows={4} /></label><button className="button button-primary form-submit" type="submit">Request Punjab counselling <span>↗</span></button><small>By submitting, you agree to be contacted about your enquiry.</small></form></div></section>;
}

export function Footer() {
  return <><footer className="site-footer"><div className="shell footer-grid"><div className="footer-about"><Brand /><p>Personal education, skill-course and WES guidance for students, professionals and families across Punjab.</p><div className="footer-language"><span>ਪੰਜਾਬੀ</span><span>English</span></div><a className="footer-consultation" href="/#enquiry">Book a free consultation <span>→</span></a></div><div><h3>Explore</h3><Link href="/">Home</Link><Link href="/#about">About Luminary</Link><Link href="/courses/#university-programs">University Programs</Link><Link href="/courses/#nursing-skill-courses">Nursing & Skill Courses</Link><Link href="/courses/#iti-trades">ITI Courses</Link><Link href="/#wes-evaluation">WES Assistance</Link></div><div><h3>Contact</h3><a href="tel:+917053732000">+91 70537 32000</a><a href="tel:+919914099906">+91 99140 99906</a><a href="mailto:luminaryedu@zohomail.com">luminaryedu@zohomail.com</a><span className="footer-service-area">Serving students across Punjab</span><a className="footer-whatsapp-link" href="https://wa.me/917053732000?text=Hello%20Luminary%2C%20I%20need%20education%20counselling.">Chat on WhatsApp →</a></div></div><div className="shell footer-bottom"><span>© 2026 Luminary Educational Services · Punjab</span><span>By Manpreet Saini</span></div></footer><a className="desktop-whatsapp" href="https://wa.me/917053732000?text=Hello%20Luminary%2C%20I%20need%20education%20counselling." target="_blank" rel="noreferrer" aria-label="Chat with Luminary on WhatsApp"><span className="whatsapp-symbol">◔</span><span><small>Need guidance?</small><strong>Chat on WhatsApp</strong></span></a><div className="mobile-actions"><a href="tel:+917053732000">Call now</a><a href="https://wa.me/917053732000?text=Hello%20Luminary%2C%20I%20need%20education%20counselling.">WhatsApp</a></div></>;
}
